<a href="https://colab.research.google.com/github/J0SAL/Learning-ML/blob/main/Codebasis/08K_FoldCrossValidation/main.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**K Fold Cross Validation**

In [41]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_iris
iris=load_iris()

In [43]:
##Example of working
from sklearn.model_selection import KFold
kf=KFold(n_splits=3)

for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


**With Explation**

In [44]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [45]:
from sklearn.model_selection import StratifiedKFold #Same as k_fold
folds = StratifiedKFold(n_splits=3)

scores_logistic = []
scores_svm = []
scores_rf = []

for train_index, test_index in folds.split(iris.data,iris.target):
    X_train, X_test, y_train, y_test = iris.data[train_index], iris.data[test_index], \
                                       iris.target[train_index], iris.target[test_index]
    scores_logistic.append(get_score(LogisticRegression(solver='liblinear',multi_class='ovr'), X_train, X_test, y_train, y_test))  
    scores_svm.append(get_score(SVC(gamma='auto'), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40), X_train, X_test, y_train, y_test))

In [46]:
scores_logistic

[0.96, 0.96, 0.94]

In [47]:
scores_svm

[0.98, 0.98, 0.96]

In [48]:
scores_rf

[0.98, 0.94, 0.96]

**Shortcut and Similar**

In [52]:
from sklearn.model_selection import cross_val_score
iris = load_iris()

**1. Logistic Regression**

In [53]:
logis_score = cross_val_score(LogisticRegression(), iris.data, iris.target);
logis_score

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

In [55]:
np.average(logis_score)

0.9733333333333334

**2. Decision Tree**

In [56]:
d_score = cross_val_score(DecisionTreeClassifier(), iris.data, iris.target);
d_score

array([0.96666667, 0.96666667, 0.9       , 1.        , 1.        ])

In [57]:
np.average(d_score)

0.9666666666666668

**3. Support Vector Machine(SVM)**

In [58]:
s_scores = cross_val_score(SVC(), iris.data, iris.target)
s_scores

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [59]:
np.average(s_scores)

0.9666666666666666

**4. Random Forest**

In [60]:
r_scores = cross_val_score(RandomForestClassifier(n_estimators=40), iris.data, iris.target)
r_scores

array([0.96666667, 0.96666667, 0.93333333, 0.93333333, 1.        ])

In [61]:
np.average(r_scores)

0.96

**Conclusion: Best Score by Logistic Regression**